import { useMemo, useState } from 'react'
import { Icon, Brandmark } from '../ui/Icon'
import { Cap, Chip } from '../ui/bits'
import { useStore } from '../app/store'
import { fmtClock, fmtDate } from '../app/util'

export function Reports() {
  const { conversations, active, activeId, openConversation, files, profile, go, toast } = useStore()
  const [signed, setSigned] = useState(false)

  const convo = active ?? conversations[0] ?? null
  const report = useMemo(() => {
    if (!convo) return null
    const observations: string[] = []
    const findings: { status: 'confirmed' | 'suspected'; text: string; confidence?: number }[] = []
    const refs: string[] = []
    convo.messages.forEach((m) => {
      m.sections?.forEach((s) => {
        if (s.kind === 'observed') observations.push(s.text)
        if (s.kind === 'inferred') {
          findings.push({ status: 'suspected', text: s.text, confidence: m.confidence })
        }
      })
      if (m.notice?.level === 'confirmed') findings.push({ status: 'confirmed', text: m.notice.title })
      m.refs?.forEach((r) => refs.push(`${r.doc} · p.${r.page}`))
    })
    return { observations, findings, refs }
  }, [convo])

  if (!convo || !report) {
    return (
      <section className="panel sheet-page">
        <div className="empty" style={{ padding: 60 }}>
          <Icon name="book" size={34} stroke="var(--vf-text-2)" width={1.4} />
          <h2 style={{ fontSize: 22 }}>No reports yet</h2>
          <p>A report is generated from a conversation once there is at least one finding.</p>
          <button type="button" className="btn primary" onClick={() => go('chat')}>Open a conversation</button>
        </div>
      </section>
    )
  }

  const attached = files.filter((f) => convo.fileIds.includes(f.id))

  return (
    <div className="doc">
      <aside className="sidebar" style={{ width: 258 }}>
        <div className="sidebar-head"><h2 style={{ fontSize: 14 }}>Reports</h2></div>
        <div className="sidebar-list">
          <Cap style={{ padding: '10px 12px 4px' }}>From your conversations</Cap>
          {conversations.map((c, i) => (
            <button
              key={c.id}
              type="button"
              className={c.id === (activeId ?? conversations[0]?.id) ? 'convo-item on' : 'convo-item'}
              onClick={() => openConversation(c.id)}
            >
              <span className="t"><span>{c.title}</span></span>
              <span className="m">
                <span>INS-{String(241 - i).padStart(4, '0')}</span>
                <span style={{ opacity: 0.45 }}>·</span>
                <span>{fmtDate(c.startedAt)}</span>
                <span style={{ opacity: 0.45 }}>·</span>
                <span>{signed && c.id === convo.id ? 'SIGNED' : 'DRAFT'}</span>
              </span>
            </button>
          ))}
        </div>
      </aside>

      <div className="doc-page">
        <article className="paper" style={{ maxWidth: 712 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 14, paddingBottom: 18, borderBottom: '2px solid var(--vf-text)', marginBottom: 22 }}>
            <Brandmark size={34} />
            <div style={{ flex: 1 }}>
              <div style={{ fontFamily: 'var(--vf-display)', fontSize: 19, fontWeight: 600 }}>Inspection report</div>
              <Cap style={{ marginTop: 3 }}>INS-0241 · Generated by VisionField Copilot</Cap>
            </div>
            <div style={{ textAlign: 'right' }}>
              <Cap>Status</Cap>
              <div style={{ marginTop: 4 }}>
                {signed
                  ? <Chip icon="check" tone="ok" size="sm">Signed</Chip>
                  : <Chip icon="pencil" tone="warn" size="sm">Draft — unsigned</Chip>}
              </div>
            </div>
          </div>

          <div className="report-block">
            <Cap>Job</Cap>
            <div className="report-kv">
              {[
                ['Machine', convo.machine ?? '[MACHINE]'],
                ['Location', '[LOCATION]'],
                ['Date & time', `${fmtDate(convo.startedAt)} · ${fmtClock(convo.startedAt)}`],
                ['Technician', profile.name || '[YOUR NAME]'],
              ].map(([k, v]) => (
                <div key={k} style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                  <Cap style={{ fontSize: 9 }}>{k}</Cap>
                  <span style={{ fontSize: 12.5, fontWeight: 500 }}>{v}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="report-block">
            <Cap>Observations</Cap>
            {report.observations.length ? (
              <ul style={{ fontSize: 12.5, lineHeight: 1.75, color: 'var(--vf-text-2)' }}>
                {report.observations.map((o, i) => <li key={i}>{o}</li>)}
              </ul>
            ) : (
              <p style={{ fontSize: 12.5, color: 'var(--vf-muted)' }}>No observations recorded in this conversation yet.</p>
            )}
          </div>

          <div className="report-block">
            <Cap>Findings</Cap>
            {report.findings.length ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
                {report.findings.map((f, i) => (
                  <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                    <Icon
                      name={f.status === 'confirmed' ? 'check' : 'sparks'}
                      size={16}
                      stroke={f.status === 'confirmed' ? 'var(--vf-ok)' : 'var(--vf-text-2)'}
                      width={f.status === 'confirmed' ? 2.1 : 1.8}
                    />
                    <div>
                      <b style={{ fontSize: 12.5 }}>
                        {f.status === 'confirmed' ? 'Confirmed' : `Suspected${f.confidence ? ` (${f.confidence}%)` : ''}`}
                      </b>
                      <div style={{ fontSize: 12, color: 'var(--vf-text-2)', lineHeight: 1.6 }}>{f.text}</div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p style={{ fontSize: 12.5, color: 'var(--vf-muted)' }}>Nothing has been concluded yet — findings appear here as they are established.</p>
            )}
          </div>

          <div className="report-block">
            <Cap>Evidence &amp; references</Cap>
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
              {attached.map((f) => <Chip key={f.id} icon="file" size="sm">{f.name}</Chip>)}
              {report.refs.map((r, i) => <Chip key={i} icon="book" size="sm">{r}</Chip>)}
              {!attached.length && !report.refs.length && (
                <span style={{ fontSize: 12.5, color: 'var(--vf-muted)' }}>No files or document references attached.</span>
              )}
            </div>
          </div>

          <div style={{ display: 'flex', gap: 40, marginTop: 26, paddingTop: 16, borderTop: '1px solid var(--vf-track)' }}>
            {['Technician', 'Reviewed by'].map((role, i) => (
              <div key={role} style={{ flex: 1 }}>
                <Cap style={{ fontSize: 9, marginBottom: 22 }}>{role}</Cap>
                <div style={{ borderBottom: '1px solid var(--vf-border-strong)' }} />
                <div style={{ fontSize: 11, color: 'var(--vf-muted)', marginTop: 5 }}>
                  {i === 0 ? (profile.name || '[YOUR NAME]') : '[NAME] · [ROLE]'}
                </div>
              </div>
            ))}
          </div>
        </article>
      </div>

      <aside className="doc-aside no-print">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
          <button type="button" className="btn wide" onClick={() => toast('Draft saved', 'Stored on this device.')}>Save draft</button>
          <button
            type="button" className="btn primary wide"
            onClick={() => { setSigned(true); toast('Report signed', 'It is now read-only and ready to export.') }}
            disabled={signed}
          >
            <Icon name="check" size={17} stroke="var(--vf-on-invert)" width={2} />
            {signed ? 'Signed' : 'Sign & finalise'}
          </button>
        </div>
        <div className="rule" />
        <Cap>Export</Cap>
        <div style={{ display: 'flex', gap: 8 }}>
          <button type="button" className="btn ghost sm grow" onClick={() => window.print()}>
            <Icon name="dl" size={15} stroke="var(--vf-text-2)" />PDF
          </button>
          <button type="button" className="btn ghost sm grow" onClick={() => window.print()}>
            <Icon name="print" size={15} stroke="var(--vf-text-2)" />Print
          </button>
        </div>
        <div className="rule" />
        <Cap>Uncertainty declared</Cap>
        <p style={{ fontSize: 12.5, lineHeight: 1.6, color: 'var(--vf-text-2)' }}>
          Unconfirmed findings print as <em>suspected</em> with their confidence, so the customer can see what
          still needs checking.
        </p>
        <span style={{ flex: 1 }} />
        <button type="button" className="btn ghost sm wide" onClick={() => go('chat')}>Back to conversation</button>
      </aside>
    </div>
  )
}
